site_name: Sinen Docs
site_url: https://astomih.github.io/sinen/
theme:
  language: en
  name: material

plugins:
  - search:
  - i18n:
      docs_structure: folder
      languages:
          - locale: en
            default: true
            name: Engligh
          - locale: ja
            name: 日本語