name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libraries
      run: |
          cd android-project/app/jni
          ln -s ../../ ./sinen
          git clone https://github.com/libsdl-org/SDL.git
          git clone https://github.com/libsdl-org/SDL_image.git
          git clone https://github.com/libsdl-org/SDL_mixer.git
          git clone https://github.com/libsdl-org/SDL_ttf.git
          git clone https://github.com/libsdl-org/SDL_net.git
          mv SDL SDL2
          mv SDL_image SDL2_image
          mv SDL_mixer SDL2_mixer
          mv SDL_ttf SDL2_ttf
          mv SDL_net SDL2_net
          mv CMakeLists-SDL_net.txt SDL2_net
          cd SDL2_net
          mv CMakeLists-SDL_net.txt CMakeLists.txt
          cd ../../../

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    

    - name: Grant execute permission for gradlew
      run: |
          pwd
          cd android-project
          chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
