name: Emscripten(Web) 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  EM_VERSION: 3.1.15

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mymindstorm/setup-emsdk@v11
    - name: CMake
      run: |
        git submodule update --init --recursive
        emcmake cmake -B build
    - name: Build
      run: |
        cd ${{github.workspace}}/build/game
        cp -r ${{github.workspace}}/game/data .
        cp ${{github.workspace}}/demo/shell_minimum.html .
        cd ${{github.workspace}}/build
        make -j2
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: web
        path: build/game
  deploy:
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: web
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: 'web'
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        target-folder: game